/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiParking;
import java.sql.*;
import java.util.*;
import javax.swing.*;
import java.sql.SQLException;
import java.sql.*;
import java.sql.ResultSet;
import java.sql.Connection;
import java.text.*;
import java.io.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author placide
 */
public class AllCars extends javax.swing.JFrame {
    ArrayList<Car> cars;
    private static final String USERNAME = "root";
    private static final String PASSWORD = "toor";
    private static final String LINK = "jdbc:mysql://localhost:3306/Car";
    /**
     * Creates new form AllCars
     */
    public AllCars() {
        initComponents();
        carParkedIn();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AllCars");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PlateNo", "Name|Type", "Model", "Entry Time", "Exit Time", "Fee Paid", "Is Car In   "
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(443, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int index= jTable1.getSelectedRow();
        DefaultTableModel df=(DefaultTableModel)jTable1.getModel();
        String plateNo= (String)df.getValueAt(index,0);
        String queryDelete = "DELETE FROM car2 WHERE plate_no='" + plateNo + "'AND is_carIn=0";

        try ( Connection conn = DriverManager.getConnection(LINK, USERNAME, PASSWORD)) {
            PreparedStatement statUpdate = conn.prepareStatement(queryDelete);

            int option = JOptionPane.showConfirmDialog(null, "Do You Want to Delete Permanent?", "warning", JOptionPane.YES_NO_OPTION);

            if (option == JOptionPane.YES_OPTION) {
                int result = statUpdate.executeUpdate();
                if (result > 0) {
                    JOptionPane.showMessageDialog(null, "Vehicle Deleted From the System");
                } else {
                    JOptionPane.showMessageDialog(null, "Vehicle not in the System or It has not paid already ");
                }

            }
           

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getStackTrace());

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void carParkedIn() {
        String QUERY = "SELECT * FROM car2";

        try ( Connection conn = DriverManager.getConnection(LINK, USERNAME, PASSWORD)) {
            PreparedStatement statement = conn.prepareStatement(QUERY);
            ResultSet result = statement.executeQuery();
            ResultSetMetaData resultData = result.getMetaData();
            int count = resultData.getColumnCount();
            DefaultTableModel df = (DefaultTableModel) jTable1.getModel();
            df.setRowCount(0);
            int carCount = 0;
            while (result.next()) {
                String plateNo = result.getString(1);
                String type = result.getString(2);
                String model = result.getString(3);
                Timestamp timeIn = result.getTimestamp(4);
                java.util.Date timeOut = result.getDate(5);
                int feePaid = result.getInt(6);
                int isCarIn = result.getInt(7);
                Vector list = new Vector();
                for (int i = 0; i < count; i++) {
                    list.add(plateNo);
                    list.add(type);
                    list.add(model);
                    list.add(timeIn);
                    list.add(timeOut);
                    list.add(feePaid);
                    list.add(isCarIn);

                }
                df.addRow(list);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Invalid Inputs");
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllCars().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
