/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiParking;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.Date;
import java.util.Scanner;
import javax.swing.*;
import java.text.*;


/**
 *
 * @author placide
 */
public class CarPark extends javax.swing.JFrame {
    private static final String USERNAME = "root";
    private static final String PASSWORD = "toor";
    private static final String LINK = "jdbc:mysql://localhost:3306/Car";
    private static String type;
    private static String plateNo;
    private static String model;
    /**
     * Creates new form CarPark
     */
    public CarPark() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu7 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        jMenu7.setText("jMenu7");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Car Park System");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\placide\\Pictures\\Saved Pictures\\IMG_20181220_135545_1CS-01.jpeg")); // NOI18N
        jLabel1.setText("jLabel1");

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText(" Close");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("InsertCar");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("SelectCar");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setText(" CarParkedIn");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu5.setText("MoveCarOut");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu6.setText("DeleteCar");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 845, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public static void insertCar() {
        Date now = new Date();
        Calendar calendar = Calendar.getInstance();
        java.sql.Date exitTime = null;
        java.util.Date date = new java.util.Date();
        java.sql.Date entryTime = new java.sql.Date(date.getTime());
        java.sql.Timestamp sqlTime = new java.sql.Timestamp(date.getTime());

        Scanner scan = new Scanner(System.in);
        System.out.print("What Type of This car or Name ?:");
        type = scan.nextLine();
        System.out.println();
        System.out.print("Please Specify the PlateNo:");
        plateNo = scan.next();
        System.out.println("Please Specify Its Model");
        System.out.println("1.Voiture | 2.Van | 3.PickUp | 4.Coaster | 5.Truck");
        int option = scan.nextInt();
        int isCarIn = 1;
        String selectQuery = "SELECT * FROM car WHERE plate_no='" + plateNo + "'";

        try ( Connection conn = DriverManager.getConnection(LINK, USERNAME, PASSWORD)) {
            PreparedStatement selectStat = conn.prepareStatement(selectQuery);
            ResultSet resultSelect = selectStat.executeQuery();
            while (resultSelect.next()) {
                System.out.println("Car is already in Our System!");
                return;
            }
            long startTime = 0;
            if (option == 1) {
                model = "Voiture";
                System.out.println("Car Parked Time:" + sqlTime);
                startTime = sqlTime.getTime();

            } else if (option == 2) {

                model = "Van";
                System.out.println("Car Parked Time:" + now);
                startTime = sqlTime.getTime();

            } else if (option == 3) {

                model = "PickUp";
                System.out.println("Car Parked Time:" + now);
                startTime = sqlTime.getTime();

            } else if (option == 4) {

                model = "Coaster";
                System.out.println("Car Parked Time:" + now);
                startTime = sqlTime.getTime();

            } else if (option == 5) {

                model = "Truck";
                System.out.println("Car Parked Time:" + now);
                startTime = sqlTime.getTime();

            } else {

                System.out.println("Invalid choice !!");
            }
            int feePaid = 0;
            String QUERY = "INSERT INTO car(plate_no,name_type,model,entryTime,exitTime,feePaid,is_CarIn)VALUES(?,?,?,?,?,?,?)";
            PreparedStatement statement = conn.prepareStatement(QUERY);
            statement.setString(1, plateNo);
            statement.setString(2, type);
            statement.setString(3, model);
            statement.setTimestamp(4, sqlTime);
            statement.setDate(5, exitTime);
            statement.setInt(6, feePaid);
            statement.setInt(7, isCarIn);
            int result = statement.executeUpdate();
            if (result > 0) {

                System.out.println("Data Inserted Successufully!!");
            }

        } catch (SQLException ex) {
            System.err.format("MYSQLSTATE:%s\n%s", ex.getSQLState(), ex.getMessage());
        } catch (Exception ex) {
//            ex.printStackTrace();
            System.out.println("Invalid inputs !:)");
        }

    }
    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        // this Where I should get insert my codes for carParked in
        new CarParkedIn().setVisible(true);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        //this is for also insertVehicle so this means that  I will having another 
       //jFrame Form so this means that building a system it is not easy
       new InsertCar().setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        //this will be mouse clicking what should happen it is to select Car
        new SelectCar().setVisible(true);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
        //this is for moving out a car 
        new MoveCarOut().setVisible(true);
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        // TODO add your handling code here:
        //this is for deleting the car
        new DeleteCar().setVisible(true);
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarPark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarPark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarPark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarPark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarPark().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
